// <auto-generated />
using ILCS_restfulAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ILCS_restfulAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231203231937_ilcs")]
    partial class ilcs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ILCS_restfulAPI.Models.Barang", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<long>("kd_tarif")
                        .HasColumnType("bigint");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("kd_tarif");

                    b.ToTable("m_barang");

                    b.HasData(
                        new
                        {
                            id = 555,
                            kd_tarif = 10079000L,
                            nama = "Butiran sorghum"
                        },
                        new
                        {
                            id = 556,
                            kd_tarif = 10079000L,
                            nama = "Tembakau"
                        },
                        new
                        {
                            id = 557,
                            kd_tarif = 10079000L,
                            nama = "Cengkeh"
                        },
                        new
                        {
                            id = 558,
                            kd_tarif = 10079111L,
                            nama = "handphone"
                        },
                        new
                        {
                            id = 559,
                            kd_tarif = 10079111L,
                            nama = "Laptop"
                        });
                });

            modelBuilder.Entity("ILCS_restfulAPI.Models.Negara", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("kd_negara")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("m_negara");

                    b.HasData(
                        new
                        {
                            id = 1,
                            kd_negara = "IDN",
                            nama = "Indonesia"
                        },
                        new
                        {
                            id = 2,
                            kd_negara = "SGP",
                            nama = "Singapore"
                        },
                        new
                        {
                            id = 3,
                            kd_negara = "IRQ",
                            nama = "Iraq"
                        },
                        new
                        {
                            id = 4,
                            kd_negara = "MYS",
                            nama = "Malaysia"
                        },
                        new
                        {
                            id = 5,
                            kd_negara = "PHL",
                            nama = "Philippines"
                        });
                });

            modelBuilder.Entity("ILCS_restfulAPI.Models.Pelabuhan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("id_negara")
                        .HasColumnType("integer");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("id_negara");

                    b.ToTable("m_pelabuhan");

                    b.HasData(
                        new
                        {
                            id = 111,
                            id_negara = 2,
                            nama = "Jurong"
                        },
                        new
                        {
                            id = 112,
                            id_negara = 2,
                            nama = "Marina"
                        },
                        new
                        {
                            id = 113,
                            id_negara = 2,
                            nama = "Keppel"
                        },
                        new
                        {
                            id = 114,
                            id_negara = 1,
                            nama = "Merak"
                        },
                        new
                        {
                            id = 115,
                            id_negara = 1,
                            nama = "Batam"
                        },
                        new
                        {
                            id = 116,
                            id_negara = 3,
                            nama = "Klang"
                        },
                        new
                        {
                            id = 117,
                            id_negara = 4,
                            nama = "Flous"
                        },
                        new
                        {
                            id = 118,
                            id_negara = 5,
                            nama = "Rafles"
                        });
                });

            modelBuilder.Entity("ILCS_restfulAPI.Models.Tarif", b =>
                {
                    b.Property<long>("kd_tarif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("kd_tarif"));

                    b.Property<double>("tarif_bm")
                        .HasColumnType("double precision");

                    b.HasKey("kd_tarif");

                    b.ToTable("m_tarif");

                    b.HasData(
                        new
                        {
                            kd_tarif = 10079000L,
                            tarif_bm = 0.10000000000000001
                        },
                        new
                        {
                            kd_tarif = 10079111L,
                            tarif_bm = 0.20000000000000001
                        });
                });

            modelBuilder.Entity("ILCS_restfulAPI.Models.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<long>("harga")
                        .HasColumnType("bigint");

                    b.Property<int>("id_barang")
                        .HasColumnType("integer");

                    b.Property<int>("id_pelabuhan")
                        .HasColumnType("integer");

                    b.Property<long>("kd_tarif")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("id_barang");

                    b.HasIndex("id_pelabuhan");

                    b.HasIndex("kd_tarif");

                    b.ToTable("t_transactions");

                    b.HasData(
                        new
                        {
                            id = 1,
                            harga = 1000000L,
                            id_barang = 555,
                            id_pelabuhan = 111,
                            kd_tarif = 10079000L
                        },
                        new
                        {
                            id = 2,
                            harga = 1200000L,
                            id_barang = 556,
                            id_pelabuhan = 112,
                            kd_tarif = 10079000L
                        },
                        new
                        {
                            id = 3,
                            harga = 1300000L,
                            id_barang = 557,
                            id_pelabuhan = 113,
                            kd_tarif = 10079000L
                        },
                        new
                        {
                            id = 4,
                            harga = 1400000L,
                            id_barang = 558,
                            id_pelabuhan = 114,
                            kd_tarif = 10079111L
                        },
                        new
                        {
                            id = 5,
                            harga = 1500000L,
                            id_barang = 559,
                            id_pelabuhan = 115,
                            kd_tarif = 10079111L
                        });
                });

            modelBuilder.Entity("ILCS_restfulAPI.Models.Barang", b =>
                {
                    b.HasOne("ILCS_restfulAPI.Models.Tarif", "Tarif")
                        .WithMany("Barang")
                        .HasForeignKey("kd_tarif")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarif");
                });

            modelBuilder.Entity("ILCS_restfulAPI.Models.Pelabuhan", b =>
                {
                    b.HasOne("ILCS_restfulAPI.Models.Negara", "Negara")
                        .WithMany("Pelabuhan")
                        .HasForeignKey("id_negara")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negara");
                });

            modelBuilder.Entity("ILCS_restfulAPI.Models.Transaction", b =>
                {
                    b.HasOne("ILCS_restfulAPI.Models.Barang", "Barang")
                        .WithMany("Transactions")
                        .HasForeignKey("id_barang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ILCS_restfulAPI.Models.Pelabuhan", "Pelabuhan")
                        .WithMany("Transactions")
                        .HasForeignKey("id_pelabuhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ILCS_restfulAPI.Models.Tarif", "Tarif")
                        .WithMany("Transactions")
                        .HasForeignKey("kd_tarif")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barang");

                    b.Navigation("Pelabuhan");

                    b.Navigation("Tarif");
                });

            modelBuilder.Entity("ILCS_restfulAPI.Models.Barang", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ILCS_restfulAPI.Models.Negara", b =>
                {
                    b.Navigation("Pelabuhan");
                });

            modelBuilder.Entity("ILCS_restfulAPI.Models.Pelabuhan", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ILCS_restfulAPI.Models.Tarif", b =>
                {
                    b.Navigation("Barang");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
